language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

addons:
  apt:
    packages:
    - libgconf-2-4

stages:
  - build
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      name: "Build production"
      script: npm run build
    - stage: deploy
      name: "Deploy production"
      script:
        - npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist
        keep_history: true
        on:
          branch: master
