name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'mkolman'
        reponame: 'cycle'
        token: ${{ secrets.GITHUB_TOKEN }}

